version: "3.7"
services:
  express:
    build: ./auth-server
    environment:
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "11776:8080"
    volumes:
      - ./public/media:/root/app/media

  caddy:
    image: abiosoft/caddy:no-stats
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./:/code
    ports:
      - "1178:2015"

  hasura:
    container_name: graphql
    image: hasura/graphql-engine:v1.0.0
    restart: always
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_ADMIN_SECRET: taara-hayate-airi
      HASURA_GRAPHQL_JWT_SECRET: ${ENCRYPTION_KEY}
      HASURA_GRAPHQL_DATABASE_URL: ${DATABASE_URL}
    ports:
      - "11775:8080"

  db:
    container_name: postgis
    image: mdillon/postgis:11-alpine
    restart: always
    environment:
      POSTGRES_USER: sipp11
      POSTGRES_PASSWORD: koala.nutshell.gis
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_USER: sipp11
    volumes:
      - pdmsdata:/var/lib/postgresql/data
    ports:
      - "25435:5432"
    command: postgres -c 'max_connections=300'


volumes:
  pdmsdata: