version: "3.7"
services:
  supplements:
    build: ./supplements
    environment:
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "11776:8080"
    volumes:
      - ./public/media:/root/app/media
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      MEDIA_DIR: ${UPLOAD_DIR}

  caddy:
    image: abiosoft/caddy:no-stats
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./:/code
    ports:
      - "1178:2015"

  redis:
     image: redis:alpine
     ports:
      - "6379:6379"

  hasura:
    container_name: graphql
    image: hasura/graphql-engine:v1.2.0-beta.2
    restart: always
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: ${ENCRYPTION_KEY}
      HASURA_GRAPHQL_DATABASE_URL: ${DATABASE_URL}
    ports:
      - "11775:8080"

  db:
    container_name: postgis
    image: mdillon/postgis:11-alpine
    restart: always
    environment:
      POSTGRES_USER: sipp11
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_USER: sipp11
    volumes:
      - goth-data:/var/lib/postgresql/data
    ports:
      - "25435:5432"
    command: postgres -c 'max_connections=300'


volumes:
  goth-data:
