[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.forwardedHeaders]
      trustedIPs = ["127.0.0.1/32", "10.1.1.50"]
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"
  [entryPoints.websecure]
    address = ":443"
    #[entryPoints.websecure.forwardedHeaders]
    #  trustedIPs = ["127.0.0.1/32", "10.1.1.50"]
    #[entryPoints.websecure.http.tls]
    #  certResolver = "myresolver"

  [entryPoints.postgresql]
     address = ":25432"

[api]
  dashboard = true

[ping]

[providers]
  # Enable the file provider to define routers / middlewares / services in file
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
  [providers.file]
    directory = "/traefik-conf"
    watch = true

[certificatesResolvers.myresolver.acme]
  email = "sipp11@gmail.com"
  storage = "/etc/traefik/acme/acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"

[pilot]
    token = "919af36f-24e1-4999-a431-d37d772169a0"

