[experimental.plugins.fail2ban]
  moduleName = "github.com/tommoulard/fail2ban"
  version = "v0.6.0"

[http]
  [http.routers]
    [http.routers.dashboard]
    entryPoints = ["websecure"]
    rule = "Host(`traffic.10z.dev`)"
    service = "api@internal"
    middlewares = "simple-auth"
    [http.routers.dashboard.tls]
      certResolver = "myresolver"

    [http.routers.healthcheck]
    entryPoints = ["web", "websecure"]
    rule = "Host(`traffic.10z.dev`) && PathPrefix(`/ping`)"
    service = "ping@internal"
    [http.routers.healthcheck.tls]
      certResolver = "myresolver"

  [http.middlewares]
    [http.middlewares.simple-auth.basicAuth]
    users = [
      "sipp11:$apr1$R73svdYc$vWZ4GiV8GHabQL0JRqDax.",
    ]

    [http.middlewares.rate-limiter.rateLimit]
    # an average of 30 requests per second is allowed.
    # a burst of 50 requests is allowed.
    average = 30
    burst = 50

    [http.middlewares.my-fail2ban]
      [http.middlewares.my-fail2ban.plugin]
        [http.middlewares.my-fail2ban.plugin.fail2ban]
          [http.middlewares.my-fail2ban.plugin.fail2ban.blacklist]
            ip = ["192.168.0.0/24"]
          [http.middlewares.my-fail2ban.plugin.fail2ban.rules]
            action = ""
            actionAbuseipdb = ""
            backend = ""
            banaction = ""
            banactionAllports = ""
            bantime = "3h"
            chain = ""
            destemail = ""
            enabled = true
            fail2banAgent = ""
            filter = ""
            findtime = "10m"
            ignorecommand = ""
            logencoding = "UTF-8"
            maxretry = 4
            mode = ""
            mta = ""
            ports = "0:8000"
            protocol = ""
            sender = ""
            urlregexp = ""
            usedns = ""
          [http.middlewares.my-fail2ban.plugin.fail2ban.whitelist]
            ip = ["::1", "127.0.0.1"]

