[http]
  [http.routers]
    [http.routers.dashboard]
    entryPoints = ["websecure"]
    rule = "Host(`traffic.10z.dev`)"
    service = "api@internal"
    middlewares = "simple-auth"
    [http.routers.dashboard.tls]
      certResolver = "myresolver"

    [http.routers.healthcheck]
    entryPoints = ["web", "websecure"]
    rule = "Host(`traffic.10z.dev`) && PathPrefix(`/ping`)"
    service = "ping@internal"
    [http.routers.healthcheck.tls]
      certResolver = "myresolver"

  [http.middlewares]
    [http.middlewares.simple-auth.basicAuth]
    users = [
      "sipp11:$apr1$R73svdYc$vWZ4GiV8GHabQL0JRqDax.",
    ]

    [http.middlewares.rate-limiter.rateLimit]
    # an average of 30 requests per second is allowed.
    # a burst of 50 requests is allowed.
    average = 30
    burst = 50
