[http]
  [http.routers]
    [http.routers.dashboard]
    rule = "Host(`traffic.10z.dev`)"
    service = "api@internal"
    middlewares = "simple-auth"
    [http.routers.dashboard.tls]
      certResolver = "myresolver"

    [http.routers.healthcheck]
    rule = "Host(`traffic.10z.dev`) && PathPrefix(`/ping`)"
    service = "ping@internal"
    [http.routers.healthcheck.tls]
      certResolver = "myresolver"

  [http.middlewares]
    [http.middlewares.compressor.compress]
    [http.middlewares.simple-auth.basicAuth]
    users = [
      "test:$apr1$SimrQ.wb$rKloZud3pWWFlxtSqc6ip/",
      "test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0",
    ]