[http]
  [http.routers]
    [http.routers.backbone-express]
    entryPoints = ["web", "websecure"]
    rule = "Host(`ssv-one.10z.dev`) && PathPrefix(`/upload`,`/login`,`/signup`,`/req-reset`,`/reset-password`)"
    service = "supplements-backbone@docker"
    [http.routers.backbone-express.tls]
       certResolver = "myresolver"

    [http.routers.gql-express]
    entryPoints = ["websecure"]
    rule = "Host(`ssv-one.10z.dev`) && PathPrefix(`/v1`,`/console`)"
    service = "graphql-backbone@docker"
    middlewares = ["rate-limiter"]
    [http.routers.gql-express.tls]
       certResolver = "myresolver"
