[http]
  [http.routers]
    [http.routers.chatbot]
    entryPoints = ["websecure"]
    rule = "Host(`ssv-one.10z.dev`) && PathPrefix(`/line-bot`,`/webhook`,`/static`)"
    service = "dev-server-chatbot@docker"
    middlewares = ["rate-limiter"]
    [http.routers.chatbot.tls]
       certResolver = "myresolver"
